import type { Metadata } from "next";
import { Nunito, Nunito_Sans, Geist } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/providers";
import { cn } from "@/lib/utils";
import Script from "next/script";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const nunitoMono = Nunito({
  variable: "--font-nunito-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Kelola Toko",
  description: "Generated by create next app",

  icons: {
    icon: "/logo-kelolatoko.png",
    shortcut: "/logo-kelolatoko.png",
    apple: "/logo-kelolatoko.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "bg-white",
        "text-black",
        nunitoSans.variable,
        nunitoMono.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body>
        <ReactQueryProvider>
          <main className="min-h-full flex flex-col">{children}</main>
        </ReactQueryProvider>

        <Toaster
          position="top-center"
          richColors
          toastOptions={{
            style: {
              width: "365px",
            },
          }}
        />

        <Script
          src="https://app.sandbox.midtrans.com/snap/snap.js"
          data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
